### PR TITLE
Moar tests

### PR DESCRIPTION
**Pull request by MylesBorins**
Building out some more tests, specifically working towards proper testing of the console implementation which requires being able to either collect the output of STDOUT or mock println! and eprintln! in `mod.rs`

Refs: https://github.com/jstime/jstime/pull/78

### CODE REVIEW

**Comment by MylesBorins** [comment]
ping @jstime/collaborators if anyone can review 😇

**Comment by ChristopherBiscardi** [comment]
A code comment on `setup()` or [`jstime::init`](https://github.com/jstime/jstime/blob/3d9a99c1c1cee7ae38d966f1f5a40e4fef5a6691/core/src/lib.rs#L13) would be cool: Being less familiar with v8 I had to go dive around the docs to figure out why it has to be initialized like this. That said, all the stuff necessary to understand is here or findable and the PR looks good to me (I know I'm not /collaborators yet, but figured I could review since it seems needed)

**Comment by MylesBorins** [comment]
@ChristopherBiscardi PTAL.

I've abstracted the setup function to a shared common module and "documented" why it exists.

TBH the mutex stuff is still a bit magical to me... copy pasted from deno... but it works 🎉

**Comment by ChristopherBiscardi** [comment]
makes sense to me.

My understanding of the Mutex is so that there's only ever one v8 initialized for the tests because rust doesn't have the equivalent of `before()` without using a [custom test framework](https://doc.rust-lang.org/unstable-book/language-features/custom-test-frameworks.html) which doesn't seem to be very widespread in usage anyway.

**Comment by MylesBorins** [comment]
This Pull Request has been open for 22 days and has not received review. As it is only adding new tests and in no way modifying the runtime I'm going to go ahead and land without review as per our new policy.

**Pull request merged**
